blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://devbolt.com/docs
    about: Check the documentation for answers
  - name: Discussions
    url: https://github.com/ModelRed/devbolt/discussions
    about: Ask questions and discuss ideas
